### ISSUE TITLE
Bug: Groups/Layers don't show up in the layermanager if the group doesnt have at least one layer added to the manager by default.

### ISSUE THREAD

**Issue by tobieumans** [leia-project/viewer#13]
If there isn't at least one layer within a group that has "defaultAddToManager"=true, the group and layers within will only show up in the layerlibrary. Adding it to the layermanager doesn't work. 

Particularly a problem for groups imported from connectors, such as Geonetwork or CKAN.

**Comment by kamielverhelst** [comment]
Fixed by #9
